### ISSUE TITLE
Add Acceptance/Functional Tests

### ISSUE THREAD

**Issue by luke-** [humhub/sharebetween#18]

**Comment by yurabakhtin** [comment]
related: https://github.com/humhub/sharebetween/issues/21#issuecomment-1468563054

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/sharebetween/pull/24.

**Comment by yurabakhtin** [comment]
@luke- 

> Thanks, do you see any open issues for this module?

Right now I don't know, but I forgot to inform you that during adding these tests I decided to allow sharing for all admins, please review this code https://github.com/humhub/sharebetween/pull/24/files#diff-70e43feb4e1298b5e8e21e530a7813799b21a55385e55c14800674b8569fb509R70, because the test admin could not share a post  from Space 1 to Space 2, because this user has no permission to create a post on the Space 2.
Also I am thinking we should check what spaces we display in the space selector to share, it seems currently we display there all spaces even where a current user has no permission to share, so we should either restrict the space selector or display some message after submit where the post was shared and where wasn't.

**Comment by luke-** [comment]
@yurabakhtin Oh yes, good point, can you please make it so that only spaces where the user is a member and has permission to post are shown there?

That the admin always has the permission is ok for me.

**Comment by yurabakhtin** [comment]
@luke- 

> can you please make it so that only spaces where the user is a member and has permission to post are shown there?

PR https://github.com/humhub/sharebetween/pull/25.
