### ISSUE TITLE
Reload required for share button to appear

### ISSUE THREAD

**Issue by Semir1212** [humhub/sharebetween#37]
HH 1.14
Share 1.0.2

**Comment by luke-** [comment]
@yurabakhtin I'm just discussing this with semir. Is there any similar issue to this?

**Comment by yurabakhtin** [comment]
@Semir1212 @luke- Fixed in PR https://github.com/humhub/sharebetween/pull/49.

> Is there any similar issue to this?

We had similar issue for `Content->state`, because right after create a Content such integer values in string format, so the comparing with `===` returns `false`. We should either use operator `==` or convert value to integer, that I did because I think better use the operator `===`.

To fix similar issue with `Content->state === X` we implemented new service in v1.14.1, so new code looks like `Content->getStateService()->isPublished()`. I have updated this module to use the new service here https://github.com/humhub/sharebetween/pull/49/commits/93f387e92efab8cffa00ad40ae865af3d92e836b.

**Comment by yurabakhtin** [comment]
I think this issue can appears for all integer columns where we compare them with operator `===`, but it is related only for new created records, but for records which are loaded from DB we already have the integer columns as real integer, i.e. for such loaded from DB records the operator `===` works correctly.

I mean a code line this:

```php
$record = new Record();
$record->load(Yii::$app->request->post());
$record->save();

$record->some_integer_column === 1; // FALSE <- here we have the current issue
$record->some_integer_column === '1'; // TRUE <- we cannot use it, because constant usually is integer
$record->some_integer_column == 1; // TRUE
(int) $record->some_integer_column === 1; // TRUE <- I prefer this solution
```

but on load from DB:

```php
$record = Record::findOne(123);

$record->some_integer_column === 1; // TRUE <- as expected
```

either it can be solved by run code `$record->refresh();` after insert new record, but I don't like this because it does a request to DB.

**Comment by yurabakhtin** [comment]
@luke- 

> Do I understand it correctly that the `$model->load(...)` sets the `int` attributes as a `string`?

Yes, please a sample on creating a Wiki Page:

![after_load_from_POST](https://github.com/humhub/sharebetween/assets/6995524/b4e84beb-3bdc-4844-b3f0-2d8488e39de9)

and the same record on load from DB:

![after_load_from_DB](https://github.com/humhub/sharebetween/assets/6995524/ed16fcfc-b013-49ba-bfb1-03287b97c104)

---

But I also reviewed the code where we set `Content->visibility` and `Content->state` on creating db record, I detected in that case we don't use `$model->load(...)`, we use there a code like `$model->visibility = Yii::$app->request->post('visibility')`, so here we had a bug and I fixed in by converting the value from `Yii::$app->request->post('visibility')` to `integer` before set it to the `$model->visibility`. And the same fix for `Content->state`. PR https://github.com/humhub/humhub/pull/6373/files.

---

> Maybe it makes sense to ask here in the Yii2 Forum/Chat, what is the best way to handle such situations?

Maybe yes, but I am not sure it will be released.

> Possibly we could query the PHPDoc or Database Column to detect type and cast to integer in load() if neccessary. What do you think? That shouldn't be a big deal or?

I don't think we should do a request to PHPDoc or Database, instead we just can compare a value with simple php function `is_numeric()` or use some custom regexp comparing like `preg_match('/^[0-9]+$/')` in order to convert such values to integer. We can do this for example inside `humhub\components\ActiveRecord::setAttributes($values)`:

```php
public function setAttributes($values, $safeOnly = true)
{
    if (is_array($values)) {
        foreach ($values as $name => $value) {
            if (preg_match('/^\d+$/', $value)) {
                $values[$name] = (int) $value;
            }
        }
    }

    parent::setAttributes($values, $safeOnly);
}
```

**Comment by luke-** [comment]
@yurabakhtin Ok, I thought of the following, but I'm not sure what effects it has, for example, in validation.  

``` 
    public function setAttributes($values, $safeOnly = true)
    {
        if (is_array($values)) {
            $schema = static::getTableSchema();
            
            foreach ($values as $name => $value) {
                if (isset($schema->columns[$name])) {
                    $values[$name] = $schema->columns[$name]->phpTypecast($value);
                }
            }
        }
        parent::setAttributes($values, $safeOnly);
    }
```
Maybe we could do something like this, only after successfully insert on all attributes provided by table schema?

**Comment by yurabakhtin** [comment]
@luke- Yes, the solution with `$schema->columns[$name]->phpTypecast($value);` is better indeed, but as I wrote above it does a request DB, but probably it will not the process slowly because usually it is a single request after load a data.

> Maybe we could do something like this, only after successfully insert on all attributes provided by table schema?

I think it would be better to do this after each load data because sometimes an integer field can be used on the creating form, which is displayed after failed validation, so we should keep values in same format in all places where they might be used.

**Comment by luke-** [comment]
> @luke- Yes, the solution with `$schema->columns[$name]->phpTypecast($value);` is better indeed, but as I wrote above it does a request DB, but probably it will not the process slowly because usually it is a single request after load a data.

I think that the table metadata are always cached and loaded.

> 
> > Maybe we could do something like this, only after successfully insert on all attributes provided by table schema?
> 
> I think it would be better to do this after each load data because sometimes an integer field can be used on the creating form, which is displayed after failed validation, so we should keep values in same format in all places where they might be used.

Hmm, I think it would have some side effects when we always convert entered inputs.

For example, what would be the result of a Number DB field + Numeric Validator when the user enters a string.

I think that the entered string is always converted directly as a number, and the expected message "Please enter a number" would never appear.

**Comment by yurabakhtin** [comment]
@luke- 

> I think that the table metadata are always cached and loaded.

Ok, then no problem to use the `static::getTableSchema()`.

> Hmm, I think it would have some side effects when we always convert entered inputs.
> For example, what would be the result of a Number DB field + Numeric Validator when the user enters a string.
> I think that the entered string is always converted directly as a number, and the expected message "Please enter a number" would never appear.

I have tested your code `static::getTableSchema()` with Number DB field + Numeric Validator on the Wiki Page field "sort order", yes you are right, in such cases if we enter some string like `qwerty` then the field value just converted to `0` and no error about wrong format:

![test_integer](https://github.com/humhub/sharebetween/assets/6995524/5936cb2d-546f-4ccb-b29a-f5dfc6332579)

but correctly it works like this now:

![validate_integer](https://github.com/humhub/sharebetween/assets/6995524/7cf9c4a8-6e33-4275-94d7-d2d35fab3790)

So yes we cannot apply the code right after loading data without insertion, maybe it can be applied only after successful validation.

---

But I am also thinking about cases when some integer fields are used on a creating form and they should be there as integer even when record is not created because of some errors like this:

When `$model->state` is string `'10'`, but `Content::STATE_DRAFT` is integer `10`:

1)

```php
if ($model->state == Content::STATE_DRAFT) {
    echo Label::warning(Yii::t('NewsModule.base', 'Draft'));
}
```

![draft_label_string](https://github.com/humhub/sharebetween/assets/6995524/d2d894f1-708e-4a1e-886e-7977310c15a6)

2) 
```php
if ($model->state === Content::STATE_DRAFT) {
    echo Label::warning(Yii::t('NewsModule.base', 'Draft'));
}
```

![draft_label_integer](https://github.com/humhub/sharebetween/assets/6995524/cc3f5187-4644-4b01-b3a0-9b167ab2c0e8)

**Comment by yurabakhtin** [comment]
@luke- Yes, I agree your solution, please review how it has been implemented in PR https://github.com/humhub/humhub/pull/6379.
